### ISSUE TITLE
Please provide a license

### ISSUE THREAD

**Issue by mpnally** [badwolf7/node-postgres-response-codes#1]
This could be a very useful little module, but I can't use it without a license. Can you please provide one? An obvious one to use would be postgres' own license: <https://www.postgresql.org/about/licence/>. Alternatives would be MIT or Apache2.0. Apologies if you already provided a license and I'm somehow not seeing it. Thanks.

**Comment by hollyos** [comment]
@mpnally I will get this added today. There is a reference to a license in the `package.json` but no actual license file in the repo. Will be using a `BSD-3-Clause` license for this project.

**Comment by hollyos** [comment]
Added [license.txt](https://github.com/badwolf7/node-postgres-response-codes/blob/master/license.txt)
